### ISSUE TITLE
Renaming a diagram does not rename the corresponding tab if it is opened

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#458] opened 2021-04-23 14:55 UTC
Steps to reproduce:
1. Create an open a diagram
2. In the explorer, rename it
3. The name correctly changes in the explore, but not on the tab of the already opened diagram (true for the user who does the rename and also for others who may be watching the same diagram)
4. Close and reopen the diagram: the new name is not correctly displayed in the tab

**Comment by pcdavid** [comment] 2021-04-23 14:56
This might be a duplicate of https://github.com/eclipse-sirius/sirius-components/issues/377, but is has no concrete scenario so not 100% sure it's the same issue.

**Comment by sbegaudeau** [comment] 2021-07-29 14:25
It is indeed a duplicate of #377, I'll paste your step to reproduce there

**Closed by sbegaudeau** 2021-07-29 14:25 UTC
Labels: area: frontend, type: bug 💥
