### ISSUE TITLE
 Improve positions and sizes of added / moved elements

### ISSUE THREAD

**Issue by mbats** [eclipse-sirius/sirius-components#233] opened 2021-01-07 15:31 UTC
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior
After deactivating the layout (#232), we should re-work the positions and sizes of added / moved elements.

- [ ] [Initialize the container size](https://github.com/eclipse-sirius/sirius-components/issues/285)
- [ ] [Move contained element](https://github.com/eclipse-sirius/sirius-components/issues/288)
- [ ] [Resize elements](https://github.com/eclipse-sirius/sirius-components/issues/289)

**Comment by sbegaudeau** [comment] 2021-03-01 09:06
Duplicate of another issue

**Closed by sbegaudeau** 2021-03-01 09:06 UTC
Labels: area: backend, area: frontend, difficulty: medium 👩‍💻, type: feature request 🤔
