### ISSUE TITLE
Renaming a diagram does not update the Navigation bar where the project name should be updated

### ISSUE THREAD

**Issue by gcoutable** [eclipse-sirius/sirius-components#467] opened 2021-04-27 12:32 UTC
### Steps to reproduce

1. Create a new project
2. From the _Project Editor View_, use the global menu to rename the project

### Expected behavior

The Navigation bar should be updated.

### Actual behavior

The Navigation bar has the previous name

**Comment by pcdavid** [comment] 2021-05-05 09:45
I think this corresponds to https://github.com/eclipse-sirius/sirius-components/issues/377

**Comment by sbegaudeau** [comment] 2021-06-10 16:58
Duplicate of another issue

**Closed by sbegaudeau** 2021-06-10 16:58 UTC
Labels: area: backend, area: frontend, type: bug 💥
