### ISSUE TITLE
Improve the layout around added / moved elements

### ISSUE THREAD

**Issue by mbats** [eclipse-sirius/sirius-components#234] opened 2021-01-07 15:32 UTC
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior
After deactivating the layout (#232), we should improve the layout around added / moved elements.

- [ ] [Improve the anchor position](https://github.com/eclipse-sirius/sirius-components/issues/286)
- [ ] [Reposition automatically the elements](https://github.com/eclipse-sirius/sirius-components/issues/287)

**Comment by sbegaudeau** [comment] 2021-03-01 09:05
Duplicate of another issue

**Closed by sbegaudeau** 2021-03-01 09:05 UTC
Labels: area: backend, area: frontend, type: feature request 🤔
